apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odoo-upgrader.fullname" . }}
  labels:
    {{- include "odoo-upgrader.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "odoo-upgrader.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "odoo-upgrader.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "odoo-upgrader.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
            - mountPath: /data
              name: data
          {{- end }}
          env:
            - name: ODOO_UPGRADER_DB_URL
              value: sqlite:////data/app.db
            - name: ODOO_UPGRADER_JOB_NAMESPACE
              value: {{ default .Release.Namespace .Values.odooUpgrader.jobNamespace }}
            - name: ODOO_UPGRADER_CONCURRENT_JOBS_LIMIT
              value: {{ .Values.odooUpgrader.concurrentJobsLimit | quote }}
            - name: ODOO_UPGRADER_JOB_ENV
              value: {{ .Values.odooUpgrader.jobEnv | toJson | quote }}
            {{- with .Values.odooUpgrader.jobSecretEnv }}
            {{- if .name }}
            - name: ODOO_UPGRADER_JOB_SECRET_ENV
              valueFrom:
                secretKeyRef:
                  name: {{ .name | quote }}
                  key: {{ .key | quote }}
            {{- end }}
            {{- end }}
            - name: ODOO_UPGRADER_JOB_DOMAIN
              value: {{ .Values.odooUpgrader.jobDomain | quote }}
            - name: ODOO_UPGRADER_UPGRADE_PATHS
              value: {{ .Values.odooUpgrader.upgradePaths | toJson | quote }}
            - name: ARGO_SERVER
              value: {{ .Values.odooUpgrader.argo.server | quote }}
            - name: ARGO_NAMESPACE
              value: {{ .Values.odooUpgrader.argo.namespace | quote }}
            - name: ARGO_SECURE
              value: {{ .Values.odooUpgrader.argo.secure | quote }}
            - name: ODOO_UPGRADER_ADMIN_PASSWORD
            {{- with .Values.odooUpgrader.adminPasswordSecret }}
            {{- if .generate }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "odoo-upgrader.fullname" $ }}
                  key: "password"
            {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .name | quote }}
                  key: {{ .key | quote  }}
            {{- end }}
            {{- end }}
            {{- with .Values.odooUpgrader.argo.secret }}
            {{- if .name }}
            - name: ARGO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .name | quote }}
                  key: {{ .key | quote }}
            {{- end }}
            {{- end }}
            {{- with .Values.odooUpgrader.s3 }}
            - name: ODOO_UPGRADER_S3__ENDPOINT
              value: {{ .endpoint | quote }}
            - name: ODOO_UPGRADER_S3__BUCKET
              value: {{ .bucket | quote }}
            - name: ODOO_UPGRADER_S3__ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .secret.name | quote }}
                  key: {{ .secret.accessKey | quote }}
            - name: ODOO_UPGRADER_S3__SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .secret.name | quote }}
                  key: {{ .secret.secretKey | quote }}
            {{- end }}
            {{- with .Values.odooUpgrader.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.volumes }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "odoo-upgrader.fullname" . }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
