{{- if .Values.odooUpgrader.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "odoo-upgrader.fullname" . }}
spec:
  resources:
    requests:
      storage: {{ .Values.odooUpgrader.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
{{- end }}